apiVersion: v1
kind: Service
metadata:
  name: redis-node-port
  namespace: infra
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30079
  selector:
    app: redis
